In [2]:
import numpy as np

In [4]:
a=np.array([1,23,4,5,6,4,2,12334,7,843,546])
a

array([    1,    23,     4,     5,     6,     4,     2, 12334,     7,
         843,   546])

In [5]:
a[0]=20
a

array([   20,    23,     4,     5,     6,     4,     2, 12334,     7,
         843,   546])

In [6]:
#slicing
s=a[3:7]
print(s)
s[0]=78888
print(a) #Main array te change hobe

[5 6 4 2]
[   20    23     4 78888     6     4     2 12334     7   843   546]


In [7]:
#But normal python e eta hoy na
b=[1,2,3,4,65,78,3]
print(b)

c=b[4:7]
c[0]=99999999
print(b)

[1, 2, 3, 4, 65, 78, 3]
[1, 2, 3, 4, 65, 78, 3]


In [8]:
a=np.array(([1,2,3],[2,2,3]))
a
a=np.array(([1,2,3],[2,2,3]))
a

array([[1, 2, 3],
       [2, 2, 3]])

In [9]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

2
(2, 3)
6
int64


In [10]:
a=np.zeros((2,3,4))
print(a)
print(a.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3


In [11]:
a=np.ones((3,4))
print(a)
a=np.empty(5)
print(a)
a=np.random.random((3,2))*100
print(a)
b=np.arange(1,10,2)
print(b)
b=np.linspace(1,100,5)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.00000000e+000 0.00000000e+000 9.40470471e-311 0.00000000e+000
 0.00000000e+000]
[[57.58526892 82.65177293]
 [94.10222603 71.14463289]
 [78.48254998 12.85795402]]
[1 3 5 7 9]
[  1.    25.75  50.5   75.25 100.  ]


In [12]:
a=np.array(3,dtype=np.int64)
print(a.dtype)

int64


In [13]:
a=np.random.random((3,2))*100
print(a)
a=np.sort(a)
a

[[38.50869407 73.1337194 ]
 [98.25006598  9.40242868]
 [88.53624027 19.61762276]]


array([[38.50869407, 73.1337194 ],
       [ 9.40242868, 98.25006598],
       [19.61762276, 88.53624027]])

In [14]:
a=np.array([1,2,34,56])
b=np.array([6,54,87,3])
c=np.concatenate((a,b))
print(c)


[ 1  2 34 56  6 54 87  3]


In [20]:
c=np.random.random((4,3))
print(c)
print(c.shape)

[[0.82525704 0.08086875 0.24951837]
 [0.78153494 0.11467356 0.7428759 ]
 [0.36805956 0.95915395 0.06349453]
 [0.42056097 0.14526487 0.14721918]]
(4, 3)


In [26]:
b=np.array([1,2,34,5,6,65,3,5,4,67,32,5])
c=b.reshape(3,4)
c

array([[ 1,  2, 34,  5],
       [ 6, 65,  3,  5],
       [ 4, 67, 32,  5]])

In [27]:
c.transpose()

array([[ 1,  6,  4],
       [ 2, 65, 67],
       [34,  3, 32],
       [ 5,  5,  5]])

In [36]:
a=c[c<5]
print(a)
b=c[c%2==0]
print(b)
d=c[(c>2) & (c<20)]
print(d)

[1 2 3 4]
[ 2 34  6  4 32]
[5 6 3 5 4 5]


In [39]:
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[5,28,34],[42,54,65]])
a3=np.vstack((a1,a2))
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5, 28, 34],
       [42, 54, 65]])

In [41]:
a3=np.hstack((a1,a2))
a3

array([[ 1,  2,  3,  5, 28, 34],
       [ 4,  5,  6, 42, 54, 65]])

In [51]:
x=np.random.random((3,4))
print(x)
np.hsplit(x,4)

[[0.8860317  0.35010917 0.98849408 0.07334709]
 [0.69220587 0.25017673 0.03117011 0.09813082]
 [0.96510509 0.44524614 0.26877699 0.88291427]]


[array([[0.8860317 ],
        [0.69220587],
        [0.96510509]]),
 array([[0.35010917],
        [0.25017673],
        [0.44524614]]),
 array([[0.98849408],
        [0.03117011],
        [0.26877699]]),
 array([[0.07334709],
        [0.09813082],
        [0.88291427]])]

In [ ]:
a=np.arange(1,4,1)
b=np.arange(4,7,1)
a+b

array([5, 7, 9])

In [63]:
a=np.random.random((2,2))
b=np.array([1,1])
a+b

array([[1.38178455, 1.39708004],
       [1.11763575, 1.35386605]])

In [70]:
a=np.random.random((2,3))
print(a)
print(a.max(axis=0))
print(a.max(axis=1))
print(a.sum(axis=0))

[[0.63700359 0.97983556 0.64067194]
 [0.9867892  0.8891492  0.09905334]]
[0.9867892  0.97983556 0.64067194]
[0.97983556 0.9867892 ]
[1.62379279 1.86898475 0.73972527]


In [75]:
unique_values, occurrence_count=np.unique(a,return_counts=True)
print(unique_values)
print(occurrence_count)
for i in range(1,unique_values.size,1):
    print(f"{unique_values[i]} -->> {occurrence_count[i]}")

[0.09905334 0.63700359 0.64067194 0.8891492  0.97983556 0.9867892 ]
[1 1 1 1 1 1]
0.6370035898216714 -->> 1
0.6406719363999619 -->> 1
0.889149196387499 -->> 1
0.9798355562884347 -->> 1
0.9867892037525137 -->> 1


In [78]:
prediction=np.random.random(10)
label=np.random.random(10)
n=20
error=(1/n)*np.sum(np.square(prediction-label))
print(error)

0.05058798230958405


In [80]:
actual=np.random.random(10)
error= -(1/n)*np.sum(actual*np.log(prediction))
error

np.float64(0.4263259386008822)

In [4]:
a=np.arange(0,10)
print(np.power(a,2))

[ 0  1  4  9 16 25 36 49 64 81]
