In [ ]:
class Employee:
    def __init__(self,name, age, position){
        self.name=name
        self.age=age
        self.position=position
    }

    def get_details(self){
        print(f"Name {self.name}, age {self.age}, position{self.positon}")
    }

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
a= np.array([1,3,34,5,67,7])
a

array([ 1,  3, 34,  5, 67,  7])

In [5]:
a[:3:2]

array([ 1, 34])

In [8]:
b=a[:4]
print(b)
b[3]=6
print(b)
print(a)

[ 1  3 34  5]
[ 1  3 34  6]
[ 1  3 34  6 67  7]


In [9]:
x=[1,3,34,5,67,7]
y=x[:4]
y[3]=6
print(y)
print(x)

[1, 3, 34, 6]
[1, 3, 34, 5, 67, 7]


In [ ]:
a=np.array([[1,2,3,4,5],[6,7,8,"9",10]])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

2
(2, 5)
10
<U21


In [40]:
b=np.zeros((7,8))
c=np.ones((7,8))
d=np.empty((5,6))
e=np.arange(1,9,2)
f=np.linspace(1,100,5)
g=np.random.random((3,2))
print(g)

[[0.36224835 0.18465036]
 [0.50958077 0.46580422]
 [0.15128623 0.84572427]]


In [41]:
h=np.sort(g)
h

array([[0.18465036, 0.36224835],
       [0.46580422, 0.50958077],
       [0.15128623, 0.84572427]])

In [43]:
i=np.concatenate((g,h))
i

array([[0.36224835, 0.18465036],
       [0.50958077, 0.46580422],
       [0.15128623, 0.84572427],
       [0.18465036, 0.36224835],
       [0.46580422, 0.50958077],
       [0.15128623, 0.84572427]])

In [ ]:
data=np.linspace(1,200,20)
print(data.reshape(4,5))
print(data.reshape(5,4))
print(data.transpose())

[[  1.          11.47368421  21.94736842  32.42105263  42.89473684]
 [ 53.36842105  63.84210526  74.31578947  84.78947368  95.26315789]
 [105.73684211 116.21052632 126.68421053 137.15789474 147.63157895]
 [158.10526316 168.57894737 179.05263158 189.52631579 200.        ]]
[[  1.          11.47368421  21.94736842  32.42105263]
 [ 42.89473684  53.36842105  63.84210526  74.31578947]
 [ 84.78947368  95.26315789 105.73684211 116.21052632]
 [126.68421053 137.15789474 147.63157895 158.10526316]
 [168.57894737 179.05263158 189.52631579 200.        ]]
[  1.          11.47368421  21.94736842  32.42105263  42.89473684
  53.36842105  63.84210526  74.31578947  84.78947368  95.26315789
 105.73684211 116.21052632 126.68421053 137.15789474 147.63157895
 158.10526316 168.57894737 179.05263158 189.52631579 200.        ]


In [ ]:
a=np.random.random((4,5))
a=a*10
a


array([[5.78949195, 9.22844974, 0.95935818, 6.0629138 , 4.80240773],
       [2.85995035, 1.59870195, 3.37173455, 6.63777594, 3.73755248],
       [6.41687306, 8.72714544, 1.88801069, 2.98346891, 7.76333867],
       [3.09081285, 8.47317342, 7.12038802, 3.30460363, 9.98284713]])

In [54]:
divisible_by_3=a[a%3==0]
divisible_by_3

array([], dtype=float64)

In [58]:
a=np.arange(1,10)
b=np.arange(11,20)
c=np.vstack((a,b))
d=np.hstack((a,b))

In [59]:
print(c)
print(d)

[[ 1  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18 19]]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]


In [60]:
x=np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [61]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [71]:
a=np.arange(1,51).reshape(5,10)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [72]:
b = a.max(axis=0)
print(b)
b=a.max(axis=1)
print(b)

[41 42 43 44 45 46 47 48 49 50]
[10 20 30 40 50]


In [84]:
c=np.array([1,2,3,2,1,2,3,4,3,2,5,6,5,4,3,2,5,4,6,5,4,3,2,3,4,4,3,2,1])
d,e=np.unique(c,return_counts="True")

In [85]:
print(d)
print(e)

[1 2 3 4 5 6]
[3 7 7 6 4 2]
